### ISSUE TITLE
Allow displaying link of attachements in posts

### ISSUE THREAD

**Issue by Technowix** [magicalraccoon/tootstream#173] opened 2018-03-09 19:37 UTC
Since https://github.com/tootsuite/mastodon/pull/6672 there is no more link to attachments in post content. 
So maybe let user know if there is an attachment and allow them to show the URL to it.

**Comment by craigmaloney** [comment] 2018-03-10 01:11
Will see if #160 addresses this.

**Comment by nightpool** [comment] 2018-03-10 19:25
dupe of https://github.com/magicalraccoon/tootstream/issues/159

**Comment by craigmaloney** [comment] 2018-05-29 12:13
This is addressed in release 0.3.4.

**Closed by craigmaloney** 2018-05-29 12:13 UTC
Labels: enhancement
