### ISSUE TITLE
provide a symlink / script as a binary to start

### ISSUE THREAD

**Issue by ng-0** [magicalraccoon/tootstream#120] opened 2017-09-09 10:02 UTC
The current way to start the application works when you install it manually via pip.
However for system-wide installations, which is what I'm working on, it's more userfriendly to provide a some other mechanism.

**Comment by craigmaloney** [comment] 2017-09-09 13:23
This is what I wanted to address with #113, but I'm currently blocked because of some outstanding pull requests. We'd need to refactor the code so it can have a way to execute the code without having to be in the same directory. 

What I currently have is:

```
#!/bin/bash
source /home/craig/.virtualenvs/tootstream/bin/activate
python3 /home/craig/projects/tootstream/tootstream/toot.py $@
```

Which is fine for my local instance but isn't ideal for a system-wide install.

So in my mind this is a duplicate of #113 and the work involved to make a Python package.

**Comment by ng-0** [comment] 2017-09-09 14:26
I see. Okay, thanks for the reply.

**Comment by craigmaloney** [comment] 2017-10-13 15:45
We've created a package for Tootstream so the need for a separate script is diminished (save for a script to activate the Python environment).

Closing this out for now.

**Closed by craigmaloney** 2017-10-13 15:45 UTC
